# Generated by Django 6.0.2 on 2026-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True),
        ),
    ]
