# Generated by Django 6.0.3 on 2026-03-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tools_used",
            new_name="tools",
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(),
        ),
    ]
