# Generated by Django 6.0.3 on 2026-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_rename_tools_used_project_tools_project_github_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(default="fas fa-code", max_length=100),
            preserve_default=False,
        ),
    ]
